### ISSUE TITLE
Container Deleting Problem

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [Shayan-Ghani/Container-Exporter#4]
I had a container that after deleting it, still displayed its related metrics in Prometheus queries. for example 
docker_container_status metric about that container collect with 0 value and 
docker_container_memory_percentage of it have some value but 
docker_container_cpu_percentage became zero.

please add metrics in unit of byte to your app too.
tnx

**Comment by Shayan-Ghani** [comment]
Thank you for bringing the issue to my attention. I will investigate and get back to you as soon as possible.

Additionally, I would greatly appreciate it if you could specify any additional features or functions by adding them to the TO-DO section in the README. Thank you.

**Comment by Shayan-Ghani** [comment]
UPDATE : 
unregistering a metric is against Prometheus policies. however, I have experimented with different implementations of containers_stats and it seems to be the prometheus_client library. to achieve what you mentioned metrics need to be unregistered whenever a container is stopped, which is under development and will be released with the tag `v1.1`  soon.
FYI, docker_container_status must remain anyway to indicate the status of the containers that have been stopped, killed, exited, etc. 
metrics in units of bytes will be added as well. 
best regards

**Comment by BrewToR** [comment]
Any updates on this :) ?
we have inconsistent data because the exporter is still sending metrics for containers that has been killed 
Thanks !

**Comment by Shayan-Ghani** [comment]
hello mate,
I have been on a quite busy schedule these days, I'll be trying my best to deliver this version ASAP, probably in the next few weeks.

**Comment by Shayan-Ghani** [comment]
The problem got fully resolved make sure you check the ChnageLog and thank you for your report again @ahmadamirahmadi007
